"""
Модуль pipeline - организация цепочки обработки новостей.

Последовательность:
1. Scout - сбор новостей из различных источников
2. Filter - фильтрация релевантных новостей через DeepSeek API
3. Copywriter - создание постов из отфильтрованных новостей

Обеспечивает логирование и отслеживание процесса на каждом этапе.
"""

from typing import List, Dict, Optional
from loguru import logger
from datetime import datetime
from pathlib import Path

# Import the service classes
from .scout_service import ScoutService
from .filter_service import FilterService
from .copywriter_service import CopywriterService
from .image_generation_service import generate_image_for_post
from .deduplication_service import DeduplicationService
from .integration_service import IntegrationService

# Create instances for module-level function calls
scout_service = ScoutService()
filter_service = FilterService()
copywriter_service = CopywriterService()
deduplication_service = DeduplicationService()
integration_service = IntegrationService()


class DigestService:
    def save_news_to_markdown(
        self, articles: List[Dict[str, str]], markdown_file: str = "news_digest.md"
    ) -> None:
        """
        Сохраняет новости с изображениями в markdown файл.

        Args:
            articles: Список статей с постами и изображениями
            markdown_file: Путь к markdown файлу
        """
        markdown_path = Path(markdown_file)

        # Создаем заголовок если файл новый
        if not markdown_path.exists():
            with open(markdown_path, "w", encoding="utf-8") as f:
                f.write("# News Digest\n\n")
                f.write("Generated by SMM Agents\n\n")
                f.write("---\n\n")

        # Добавляем новые статьи в конец файла
        with open(markdown_path, "a", encoding="utf-8") as f:
            f.write(f"## Digest от {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")

            for idx, article in enumerate(articles, 1):
                logger.debug(f"Сохраняем статью в markdown: {article.keys()}")
                logger.debug(
                    f"post_content длина: {len(article.get('post_content', ''))}"
                )

                f.write(f"### {idx}. {article['title']}\n\n")

                # Добавляем изображение если есть
                if article.get("image_path"):
                    # Используем относительный путь для markdown
                    image_path = Path(article["image_path"]).name
                    f.write(f"![Изображение](./{image_path})\n\n")

                f.write(f"**Источник:** [{article['url']}]({article['url']})\n\n")

                # Проверяем есть ли контент поста
                post_content = article.get("post_content", "")
                if post_content:
                    f.write(f"{post_content}\n\n")
                else:
                    # Если нет post_content, используем summary как fallback
                    summary = article.get("summary", "")
                    if summary:
                        f.write(f"**Краткое содержание:**\n{summary}\n\n")
                    else:
                        f.write("Содержание недоступно.\n\n")

                f.write("---\n\n")

            f.write("\n")

        logger.info(f"✅ Сохранено {len(articles)} новостей в {markdown_path}")


class NewsPipeline:
    """
    Класс для управления цепочкой обработки новостей.

    Координирует работу всех агентов и обеспечивает передачу данных между ними.
    """

    def __init__(
        self,
        deepseek_api_key: str,
        image_config: Optional[Dict] = None,
        filter_system_prompt: Optional[str] = None,
        filter_user_prompt: Optional[str] = None,
        copywriter_system_prompt: Optional[str] = None,
        copywriter_user_prompt: Optional[str] = None,
    ):
        """
        Инициализация pipeline с настройками DeepSeek API и генерации изображений.

        Args:
            deepseek_api_key: API ключ DeepSeek
            image_config: Конфигурация для генерации изображений
            filter_system_prompt: Системный промпт для фильтра (опционально)
            filter_user_prompt: Пользовательский промпт для фильтра (опционально)
            copywriter_system_prompt: Системный промпт для копирайтера (опционально)
            copywriter_user_prompt: Пользовательский промпт для копирайтера (опционально)
        """
        self.deepseek_api_key = deepseek_api_key
        self.image_config = image_config or {}
        self.filter_system_prompt = filter_system_prompt
        self.filter_user_prompt = filter_user_prompt
        self.copywriter_system_prompt = copywriter_system_prompt
        self.copywriter_user_prompt = copywriter_user_prompt
        self.integration_service = IntegrationService()

    def run_scout_stage(
        self,
        keywords: List[str],
        google_api: Optional[str] = None,
        google_cse: Optional[str] = None,
        rss_feeds: Optional[List[str]] = None,
        rss_hours: int = 72,
        max_per_source: int = 5,
    ) -> List[Dict[str, str]]:
        """
        Этап 1: Сбор новостей через Scout агента.

        Args:
            keywords: Ключевые слова для поиска
            google_api: Google API ключ
            google_cse: Google Custom Search Engine ID
            rss_feeds: Список RSS лент
            rss_hours: Период в часах для RSS
            max_per_source: Максимум статей с источника

        Returns:
            List[Dict]: Собранные статьи
        """
        logger.info("🔍 Этап 1: Начинаем сбор новостей (Scout)")

        articles = scout_service.collect_insights(
            keywords=keywords,
            google_api=google_api,
            google_cse=google_cse,
            rss_feeds=rss_feeds,
            rss_hours=rss_hours,
            max_per_source=max_per_source,
        )

        logger.info(f"✅ Scout: собрано {len(articles)} статей")

        # Удаляем дубликаты сразу после сбора
        unique_articles = deduplication_service.deduplicate_articles(articles)

        return unique_articles

    def run_filter_stage(self, articles: List[Dict[str, str]]) -> List[Dict[str, str]]:
        """
        Этап 2: Фильтрация релевантных новостей через Filter агента.

        Args:
            articles: Статьи от Scout агента

        Returns:
            List[Dict]: Отфильтрованные статьи
        """
        logger.info("🔍 Этап 2: Начинаем фильтрацию новостей (Filter)")

        if not articles:
            logger.warning("⚠️ Нет статей для фильтрации")
            return []

        filtered_articles = filter_service.filter_news(
            articles=articles,
            deepseek_api_key=self.deepseek_api_key,
            system_prompt=self.filter_system_prompt,
            user_prompt=self.filter_user_prompt,
        )

        logger.info(
            f"✅ Filter: прошло фильтр {len(filtered_articles)} из {len(articles)} статей"
        )
        return filtered_articles

    def run_copywriter_stage(
        self, articles: List[Dict[str, str]], max_posts: int = 8
    ) -> List[Dict[str, str]]:
        """
        Этап 3: Создание постов через Copywriter агента.

        Args:
            articles: Отфильтрованные статьи от Filter агента
            max_posts: Максимальное количество постов для создания

        Returns:
            List[Dict]: Статьи с созданными постами
        """
        logger.info("✍️ Этап 3: Начинаем создание постов (Copywriter)")

        if not articles:
            logger.warning("⚠️ Нет статей для создания постов")
            return []

        # Ограничиваем количество статей до максимума
        articles_to_process = articles[:max_posts]
        if len(articles) > max_posts:
            logger.info(
                f"📊 Выбираем ТОП-{max_posts} самых интересных статей из {len(articles)} отфильтрованных"
            )

        articles_with_posts = []

        for idx, article in enumerate(articles_to_process, 1):
            interest_score = article.get("interest_score", 0)
            logger.debug(
                f"Создаем пост для статьи {idx}/{len(articles_to_process)} (оценка {interest_score}/10): {article['title'][:50]}..."
            )

            try:
                copywriter_result = copywriter_service.call_deepseek_copywriter(
                    article=article,
                    deepseek_api_key=self.deepseek_api_key,
                    system_prompt=self.copywriter_system_prompt,
                    user_prompt=self.copywriter_user_prompt,
                )

                # Добавляем созданный пост и идею изображения к статье
                article_with_post = article.copy()
                article_with_post["post_content"] = copywriter_result["post"]
                article_with_post["image_idea"] = copywriter_result["image_idea"]
                articles_with_posts.append(article_with_post)

                logger.debug(
                    f"✅ Пост создан для: {article['title'][:50]}... (рейтинг {interest_score}/10)"
                )

            except Exception as e:
                logger.error(
                    f"❌ Ошибка создания поста для {article['title'][:50]}...: {e}"
                )
                continue

        logger.info(
            f"✅ Copywriter: создано {len(articles_with_posts)} постов из {len(articles_to_process)} ТОП статей (всего отфильтровано: {len(articles)})"
        )
        return articles_with_posts

    def run_image_generator_stage(
        self, articles: List[Dict[str, str]]
    ) -> List[Dict[str, str]]:
        """
        Этап 4: Генерация изображений для постов через OpenAI DALL-E.

        Args:
            articles: Статьи с постами от Copywriter агента

        Returns:
            List[Dict]: Статьи с изображениями
        """
        logger.info("🎨 Этап 4: Начинаем генерацию изображений (OpenAI DALL-E)")

        if not articles:
            logger.warning("⚠️ Нет статей для генерации изображений")
            return []

        if not self.image_config.get("enabled", False):
            logger.info("ℹ️ Генерация изображений отключена")
            return articles

        # Получаем API key для OpenAI
        openai_api_key = self.image_config.get("openai_api_key")
        if not openai_api_key:
            logger.error("❌ Не указан OpenAI API key для генерации изображений")
            return articles

        articles_with_images = []

        for idx, article in enumerate(articles, 1):
            logger.debug(
                f"Генерируем изображение для статьи {idx}/{len(articles)}: {article['title'][:50]}..."
            )

            try:
                # Генерируем изображение используя идею от копирайтера
                image_path = generate_image_for_post(
                    image_idea=article["image_idea"],
                    api_key=openai_api_key,
                    **self.image_config,
                )

                # Добавляем путь к изображению
                article_with_image = article.copy()
                article_with_image["image_path"] = image_path
                articles_with_images.append(article_with_image)

                if image_path:
                    logger.debug(f"✅ Изображение создано: {image_path}")
                else:
                    logger.debug("❌ Не удалось создать изображение")

            except Exception as e:
                logger.error(
                    f"❌ Ошибка генерации изображения для {article['title'][:50]}...: {e}"
                )
                # Добавляем статью без изображения
                article_copy = article.copy()
                article_copy["image_path"] = None
                articles_with_images.append(article_copy)

        successful_images = len(
            [a for a in articles_with_images if a.get("image_path")]
        )
        logger.info(
            f"✅ Генерация изображений: создано {successful_images} из {len(articles)} изображений"
        )

        return articles_with_images

    def run_full_pipeline(
        self,
        keywords: List[str],
        google_api: Optional[str] = None,
        google_cse: Optional[str] = None,
        rss_feeds: Optional[List[str]] = None,
        rss_hours: int = 72,
        max_per_source: int = 5,
    ) -> List[Dict[str, str]]:
        """
        Запускает полную цепочку обработки: Scout → Filter → Copywriter.

        Args:
            keywords: Ключевые слова для поиска
            google_api: Google API ключ
            google_cse: Google Custom Search Engine ID
            rss_feeds: Список RSS лент
            rss_hours: Период в часах для RSS
            max_per_source: Максимум статей с источника

        Returns:
            List[Dict]: Финальные статьи с постами
        """
        # Создаем запись о запуске дайджеста
        digest_run = self.integration_service.create_digest_run()

        logger.info("🚀 Запускаем полную цепочку обработки новостей")
        pipeline_start_time = logger.bind(stage="pipeline").info

        # Этап 1: Scout - сбор новостей
        articles = self.run_scout_stage(
            keywords=keywords,
            google_api=google_api,
            google_cse=google_cse,
            rss_feeds=rss_feeds,
            rss_hours=rss_hours,
            max_per_source=max_per_source,
        )

        if not articles:
            logger.warning("⚠️ Pipeline остановлен: Scout не нашел статей")
            self.integration_service.update_digest_run_stats(
                digest_run, status="failed", error_message="Scout не нашел статей"
            )
            return []

        # Сохраняем собранные статьи в базу
        self.integration_service.save_articles_to_db(digest_run, articles)

        # Этап 2: Filter - фильтрация релевантных
        filtered_articles = self.run_filter_stage(articles)

        if not filtered_articles:
            logger.warning("⚠️ Pipeline остановлен: Filter не пропустил ни одной статьи")
            self.integration_service.update_digest_run_stats(
                digest_run,
                total_collected=len(articles),
                status="failed",
                error_message="Filter не пропустил ни одной статьи",
            )
            return []

        # Обновляем статистику
        self.integration_service.update_digest_run_stats(
            digest_run,
            total_collected=len(articles),
            total_filtered=len(filtered_articles),
        )

        # Этап 3: Copywriter - создание постов (максимум 8)
        articles_with_posts = self.run_copywriter_stage(filtered_articles, max_posts=8)

        if not articles_with_posts:
            logger.warning(
                "⚠️ Pipeline остановлен: Copywriter не создал ни одного поста"
            )
            self.integration_service.update_digest_run_stats(
                digest_run,
                total_collected=len(articles),
                total_filtered=len(filtered_articles),
                status="failed",
                error_message="Copywriter не создал ни одного поста",
            )
            return []

        # Этап 4: Image Generator - создание изображений
        final_articles = self.run_image_generator_stage(articles_with_posts)

        # Сохраняем посты в базу данных
        self.integration_service.save_generated_posts(final_articles)

        # Обновляем финальную статистику
        successful_images = len([a for a in final_articles if a.get("image_path")])
        self.integration_service.update_digest_run_stats(
            digest_run,
            total_collected=len(articles),
            total_filtered=len(filtered_articles),
            total_posts=len(articles_with_posts),
            total_images=successful_images,
            status="completed",
        )

        # Итоговая статистика
        logger.info("🎉 Pipeline завершен успешно!")
        logger.info(
            f"📊 Статистика: {len(articles)} собрано → {len(filtered_articles)} отфильтровано → {len(articles_with_posts)} постов → {successful_images} изображений"
        )

        return final_articles


def run_news_pipeline(
    keywords: List[str],
    deepseek_api_key: str,
    google_api: Optional[str] = None,
    google_cse: Optional[str] = None,
    rss_feeds: Optional[List[str]] = None,
    rss_hours: int = 72,
    max_per_source: int = 5,
    image_config: Optional[Dict] = None,
    save_to_markdown: bool = True,
    markdown_file: str = "news_digest.md",
) -> List[Dict[str, str]]:
    """
    Упрощенная функция для запуска полной цепочки обработки новостей.

    Args:
        keywords: Ключевые слова для поиска
        deepseek_api_key: API ключ DeepSeek
        google_api: Google API ключ
        google_cse: Google Custom Search Engine ID
        rss_feeds: Список RSS лент
        rss_hours: Период в часах для RSS фильтрации
        max_per_source: Максимум статей с источника
        image_config: Конфигурация для генерации изображений
        save_to_markdown: Сохранять ли результаты в markdown файл
        markdown_file: Путь к markdown файлу

    Returns:
        List[Dict]: Готовые посты с изображениями
    """
    # Создаем запись о запуске дайджеста
    digest_run = integration_service.create_digest_run()

    pipeline = NewsPipeline(
        deepseek_api_key=deepseek_api_key,
        image_config=image_config,
    )

    results = pipeline.run_full_pipeline(
        keywords=keywords,
        google_api=google_api,
        google_cse=google_cse,
        rss_feeds=rss_feeds,
        rss_hours=rss_hours,
        max_per_source=max_per_source,
    )

    # Сохраняем результаты в markdown файл
    if save_to_markdown and results:
        digest_service = DigestService()
        digest_service.save_news_to_markdown(results, markdown_file)

        # Сохраняем посты в базу данных
        integration_service.save_generated_posts(results)

        # Обновляем статистику
        successful_images = len([a for a in results if a.get("image_path")])
        integration_service.update_digest_run_stats(
            digest_run,
            total_collected=len(
                results
            ),  # This is a simplification, in reality we'd track all stages
            total_filtered=len(results),
            total_posts=len(results),
            total_images=successful_images,
            status="completed",
        )

    return results


def run_news_pipeline_with_tracking(
    keywords: List[str],
    deepseek_api_key: str,
    google_api: Optional[str] = None,
    google_cse: Optional[str] = None,
    rss_feeds: Optional[List[str]] = None,
    rss_hours: int = 72,
    max_per_source: int = 5,
    image_config: Optional[Dict] = None,
    save_to_markdown: bool = True,
    markdown_file: str = "news_digest.md",
) -> Dict[str, List[Dict[str, str]]]:
    """
    Функция для запуска полной цепочки с детальным отслеживанием каждого этапа.

    Args:
        keywords: Ключевые слова для поиска
        deepseek_api_key: API ключ DeepSeek
        google_api: Google API ключ
        google_cse: Google Custom Search Engine ID
        rss_feeds: Список RSS лент
        rss_hours: Период в часах для RSS фильтрации
        max_per_source: Максимум статей с источника
        image_config: Конфигурация для генерации изображений
        save_to_markdown: Сохранять ли результаты в markdown файл
        markdown_file: Путь к markdown файлу

    Returns:
        Dict: {
            "all_news": все собранные новости,
            "filtered_news": отфильтрованные новости,
            "final_posts": финальные посты
        }
    """
    # Создаем запись о запуске дайджеста
    digest_run = integration_service.create_digest_run()

    pipeline = NewsPipeline(
        deepseek_api_key=deepseek_api_key,
        image_config=image_config,
    )

    logger.info("🚀 Запускаем полную цепочку обработки новостей с отслеживанием")

    # Этап 1: Scout - сбор новостей (включает дедупликацию)
    all_news = pipeline.run_scout_stage(
        keywords=keywords,
        google_api=google_api,
        google_cse=google_cse,
        rss_feeds=rss_feeds,
        rss_hours=rss_hours,
        max_per_source=max_per_source,
    )

    if not all_news:
        logger.warning("⚠️ Pipeline остановлен: Scout не нашел статей")
        integration_service.update_digest_run_stats(
            digest_run, status="failed", error_message="Scout не нашел статей"
        )
        return {"all_news": [], "filtered_news": [], "final_posts": []}

    # Сохраняем собранные статьи в базу
    integration_service.save_articles_to_db(digest_run, all_news)

    # Получаем все статьи с результатами фильтрации (включая отклоненные)
    all_news_with_filter = filter_service.get_all_articles_with_filter_results(
        all_news, pipeline.deepseek_api_key
    )

    # Этап 2: Filter - фильтрация релевантных
    filtered_news = pipeline.run_filter_stage(all_news)

    if not filtered_news:
        logger.warning("⚠️ Pipeline остановлен: Filter не пропустил ни одной статьи")
        integration_service.update_digest_run_stats(
            digest_run,
            total_collected=len(all_news),
            status="failed",
            error_message="Filter не пропустил ни одной статьи",
        )
        return {
            "all_news": all_news_with_filter,
            "filtered_news": [],
            "final_posts": [],
        }

    # Обновляем статистику
    integration_service.update_digest_run_stats(
        digest_run, total_collected=len(all_news), total_filtered=len(filtered_news)
    )

    # Этап 3: Copywriter - создание постов (максимум 8 самых интересных)
    articles_with_posts = pipeline.run_copywriter_stage(filtered_news, max_posts=8)

    if not articles_with_posts:
        logger.warning("⚠️ Pipeline остановлен: Copywriter не создал ни одного поста")
        integration_service.update_digest_run_stats(
            digest_run,
            total_collected=len(all_news),
            total_filtered=len(filtered_news),
            status="failed",
            error_message="Copywriter не создал ни одного поста",
        )
        return {
            "all_news": all_news_with_filter,
            "filtered_news": filtered_news,
            "final_posts": [],
        }

    # Этап 4: Image Generator - создание изображений
    final_posts = pipeline.run_image_generator_stage(articles_with_posts)

    # Сохраняем результаты в markdown файл
    if save_to_markdown and final_posts:
        digest_service = DigestService()
        digest_service.save_news_to_markdown(final_posts, markdown_file)

    # Сохраняем посты в базу данных
    integration_service.save_generated_posts(final_posts)

    # Обновляем финальную статистику
    successful_images = len([a for a in final_posts if a.get("image_path")])
    integration_service.update_digest_run_stats(
        digest_run,
        total_collected=len(all_news),
        total_filtered=len(filtered_news),
        total_posts=len(articles_with_posts),
        total_images=successful_images,
        status="completed",
    )

    # Итоговая статистика
    logger.info("🎉 Pipeline завершен успешно!")
    logger.info(
        f"📊 Статистика: {len(all_news)} собрано → {len(filtered_news)} отфильтровано → {len(articles_with_posts)} постов → {successful_images} изображений"
    )

    return {
        "all_news": all_news_with_filter,  # Теперь включает результаты фильтрации
        "filtered_news": filtered_news,
        "final_posts": final_posts,
    }
