# Generated by Django 5.2.7 on 2025-10-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesource',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'RSS источник', 'verbose_name_plural': 'RSS источники'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['priority', 'keyword'], 'verbose_name': 'Ключевое слово (Google CSE)', 'verbose_name_plural': 'Ключевые слова (Google CSE)'},
        ),
        migrations.RemoveIndex(
            model_name='articlesource',
            name='digest_arti_source__eece00_idx',
        ),
        migrations.RemoveField(
            model_name='articlesource',
            name='source_type',
        ),
        migrations.AlterField(
            model_name='articlesource',
            name='name',
            field=models.CharField(help_text="Название RSS ленты (например, 'Python.org Blog')", max_length=200, verbose_name='Название RSS источника'),
        ),
        migrations.AlterField(
            model_name='articlesource',
            name='url',
            field=models.URLField(blank=True, help_text='Полный URL RSS фида (например, https://www.python.org/feeds/python.rss/)', max_length=500, null=True, verbose_name='URL RSS ленты'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(help_text='Ключевое слово для поиска через Google Custom Search', max_length=200, verbose_name='Ключевое слово (для Google CSE)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='enable_google_news',
            field=models.BooleanField(default=False, help_text='Поиск статей через Google CSE по ключевым словам (настраиваются ниже)', verbose_name='Включить Google Custom Search'),
        ),
        migrations.AlterField(
            model_name='project',
            name='enable_rss_news',
            field=models.BooleanField(default=True, help_text='Сбор статей из RSS лент (источники настраиваются ниже)', verbose_name='Включить RSS сбор'),
        ),
    ]
