# Generated by Django 5.2.7 on 2025-10-16 09:49

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="openai_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True, verbose_name="OpenAI API Key"
            ),
        ),
    ]
